### ISSUE TITLE
Getting error when run npm serve -o

### ISSUE THREAD

**Issue by login2ashishverma** [DeborahK/Angular-Routing#7]
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (F:\APM\APM-Final\node_modules\@angular\cli\models\workspace-loader.j
s:37:19)
    at WorkspaceLoader.loadWorkspace (F:\APM\APM-Final\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (F:\APM\APM-Final\node_modules\@angular\cli\models\architect-command.js:19
5:32)
    at ServeCommand.<anonymous> (F:\APM\APM-Final\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at F:\APM\APM-Final\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (F:\APM\APM-Final\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (F:\APM\APM-Final\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (F:\APM\APM-Final\node_modules\@angular\cli\models\command-runner.js:87:23)

**Comment by DeborahK** [comment]
It looks like you are trying to use the Angular CLI with this project. This project was done *before* the CLI was finished and is *not* set up for use with the CLI.

Instead, follow the instructions in the course to install the packages. Then use 'npm start' to start the application.
